### ISSUE TITLE
Highlight date in bb code ?

### ISSUE THREAD

**Issue by RadekHavelka** [rosmanov/CodeMirror-modes#1]
Hello,
  I would like to thank you for this library of bbcode parsing for codemirror. I would love to extend this to highlight date in format dd.mm.yyyy (numeric values, just this format, no other) as well, same style as bb code is highlighted. I have not such skills to do it from scratch, can you maybe point me in a direction ?
  Thanks a lot

**Comment by rosmanov** [comment]
Something like this:

``` javascript
    tokenizer: function (stream, state) {
      if (stream.eatSpace()) return null;

      if (stream.match('[', true)) {
        state.tokenize = parsers.bbcode;
        return helpers.cont("tag", "startTag");
      }

      if (stream.match(/\b\d\d\.\d\d\.\d{4}\b/, true)) {
        return helpers.cont("variable-3", "variable-3");
      }

      stream.next();
      return null;
    },
```

**Comment by RadekHavelka** [comment]
great, thanks a lot !!! This is what I did :

``` javascript
 if (stream.match(/^((\d{1,2})|dd|DD)\.((\d{1,2})|mm|MM)\.((\d{4})|rrrr|RRRR|YYYY)/)) {
        return "tag";
 }
```

so it matches our specific DD.04.2014 formats for day,month or year uknown.
